--- #YAML:1.0
name:                LWP-Protocol-socks
version:             1.5
abstract:            adds support for the socks protocol and proxy facility
license:             ~
author:              
    - Sheridan C Rawlins <sheridan.rawlins@yahoo.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    IO::Socket::Socks:             0.2
    IO::Socket::SSL:               0.96
    LWP:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
