--- #YAML:1.0
name:                LWP-Protocol-socks
version:             1.2
abstract:            adds support for the socks protocol and proxy facility
license:             ~
author:              
    - Sheridan Rawlins <scr@corp.yahoo.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    IO::Socket::Socks:             0.1
    IO::Socket::SSL:               0.96
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
